spring:
  main:
    web-application-type: NONE

client:
  server-base-url: "http://localhost:8080"

---
spring:
  config:
    activate:
      on-profile: "!default"

client:
  server-base-url: "https://localhost:8443"
  ssl-bundle: test-cert

---
spring:
  config:
    activate:
      on-profile: "p12"
  ssl:
    bundle:
      jks:
        test-cert:
          truststore:
            location: "classpath:server-trust.p12"
            password: "secret"

---
spring:
  config:
    activate:
      on-profile: "p12-mtls"
  ssl:
    bundle:
      jks:
        test-cert:
          keystore:
            location: "classpath:client.p12"
            password: "secret"
          truststore:
            location: "classpath:server-trust.p12"
            password: "secret"

---
spring:
  config:
    activate:
      on-profile: "pem"
  ssl:
    bundle:
      pem:
        test-cert:
          truststore:
            certificate: "classpath:server.crt"

---
spring:
  config:
    activate:
      on-profile: "pem-mtls"
  ssl:
    bundle:
      pem:
        test-cert:
          keystore:
            certificate: "classpath:client.crt"
            private-key: "classpath:client.key"
          truststore:
            certificate: "classpath:server.crt"

---
spring:
  config:
    activate:
      on-profile: "pem-ca-mtls"
  ssl:
    bundle:
      pem:
        test-cert:
          keystore:
            certificate: "classpath:client.crt"
            private-key: "classpath:client.key"
          truststore:
            certificate: "classpath:root-ca.crt"
          key:
            alias: "ssl"
