spring:
  main:
    web-application-type: NONE

client:
  server-base-url: "http://localhost:8080"

---
spring:
  config:
    activate:
      on-profile: "!default"

client:
  server-base-url: "https://localhost:8443"
  ssl-bundle: test-cert

---
spring:
  config:
    activate:
      on-profile: "p12"
  ssl:
    jks:
      test-cert:
        trust-store: "classpath:server-trust.p12"
        trust-store-password: "secret"

---
spring:
  config:
    activate:
      on-profile: "pem"
  ssl:
    certificate:
      test-cert:
        trust-certificate: "classpath:server.crt"

---
spring:
  config:
    activate:
      on-profile: "p12-mtls"
  ssl:
    jks:
      test-cert:
        key-store: "classpath:client.p12"
        key-store-password: "secret"
        trust-store: "classpath:server-trust.p12"
        trust-store-password: "secret"

---
spring:
  config:
    activate:
      on-profile: "pem-mtls"
  ssl:
    certificate:
      test-cert:
        certificate: "classpath:client.crt"
        certificate-private-key: "classpath:client.key"
        trust-certificate: "classpath:server.crt"

---
spring:
  config:
    activate:
      on-profile: "pem-ca-mtls"
  ssl:
    certificate:
      test-cert:
        certificate: "classpath:client.crt"
        certificate-private-key: "classpath:client.key"
        trust-certificate: "classpath:root-ca.crt"
