server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: "!default"

server:
  port: 8443
  ssl:
    bundle: "test-cert"
management:
  server:
    ssl:
      bundle: "test-cert"

---
spring:
  config:
    activate:
      on-profile: "p12"
  ssl:
    bundle:
      jks:
        test-cert:
          keystore:
            location: "classpath:server.p12"
            password: "secret"
            type: "PKCS12"
          key:
            alias: "spring-boot-server"

---
spring:
  config:
    activate:
      on-profile: "pem"
  ssl:
    bundle:
      pem:
        test-cert:
          keystore:
            certificate: "classpath:server.crt"
            private-key: "classpath:server.key"

---
spring:
  config:
    activate:
      on-profile: "p12-mtls"
  ssl:
    bundle:
      jks:
        test-cert:
          keystore:
            location: "classpath:server.p12"
            password: "secret"
            type: "PKCS12"
          key:
            alias: "spring-boot-server"
          truststore:
            location: "classpath:client-trust.p12"
            password: "secret"
            type: "PKCS12"

server:
  ssl:
    client-auth: "NEED"

---
spring:
  config:
    activate:
      on-profile: "pem-mtls"
  ssl:
    bundle:
      pem:
        test-cert:
          keystore:
            certificate: "classpath:server.crt"
            private-key: "classpath:server.key"
          truststore:
            certificate: "classpath:client.crt"

server:
  ssl:
    client-auth: "NEED"

---
spring:
  config:
    activate:
      on-profile: "pem-ca-mtls"
  ssl:
    bundle:
      pem:
        test-cert:
          keystore:
            certificate: "classpath:server.crt"
            private-key: "classpath:server.key"
          truststore:
            certificate: "classpath:root-ca.crt"

server:
  ssl:
    client-auth: "NEED"
